#! /usr/bin/env bash

source ./option_parser

readonly PROG_NAME="$(basename "$BASH_SOURCE")"

usage() {

	>&2 echo "$PROG_NAME -s|--search|--find arg1 arg2 [arg3] -m|--make|--create suboption|subopt ..."
	exit 1
}

test_parser() {

	parse_options \
		',' 'OPTIONS' 'ARG_CNT' 'ARGS' 'self' '0' ';' '--'  \
		'-s'        , '--search' , '--find'    '1 1 -1'     \
		'-m'        , '--make'   , '--create'  '0'          \
		'suboption' , 'subopt'                 'S'          \
		';' \
		"$@"

	error_code=$?
	echo "$error_code"

	if [ $error_code -ne 0 ]; then
		option_parser_error_msg "$error_code" 'OPTIONS'
		usage
	fi

	for key in "${!OPTIONS[@]}"; do
		echo "OPTION --> $key"
		if [ -n "${ARG_CNT[$key]}" ] ;then
			echo "ARGS ----> $key:"
			for pos in $( seq 0 ${ARG_CNT[$key]} ) ;do
				echo "ARG[$key][$pos] -------> ${ARGS[$key,$pos]}"
			done
		fi
	done

}

test_parser "$@" 
